apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapier-deployment
  #namespace: mhdanh
spec:
  replicas: 1
  selector:
    matchLabels:              # tells what pods the deployment will apply to, refer to line number 11 for pod template
      app: zapier
  template:                   # actually, this is the pod template, describes a pod that is launched
    metadata:
      labels:
        app: zapier # this should match with the matchLabels value above, otherwise, this kind of pod will not be controlled by the above deployment
    spec:
      containers:
      - name: zapier-container
        image: asia.gcr.io/mhdanh-hello-kubernete/zapier-jenkin:v1
        # Add opening port
        ports:                                      #+
        - containerPort: 8080                       #+
          name: http                                #+
        - containerPort: 9990                       #+
          name: http-admin                          #+
---
apiVersion: v1
kind: Service
metadata:
  name: zapier-service
  #namespace: mhdanh
spec:
  type: LoadBalancer
#  type: NodePort
  selector:
    app: zapier
  ports:
  - port: 9990
    targetPort: 9990
    protocol: TCP
